rom turtle import *
bgcolor("light pink")
pensize(3)
color("red")
begin_fill()
left(50)
forward(240)
circle(100,180)
left(260)
circle(100,180)
forward(240)
end_fill()
penup()
goto(-120,160)
pendown()
color('white')
write("ICH LIEBE DICH",font=("Verdana",11,"bold italic"))
penup()
goto(-30,100)
pendown()
color('white')
write("TE QUIERO",font=("Verdana",11,"bold italic"))
penup()
goto(-70,250)
pendown()
color('white')
write(" I LOVE YOU \nTASSANOU",font=("Verdana",11,"bold italic"))
penup()
goto(-20,210)
pendown()
color('white')
write(" JE T'AIME",font=("Verdana",11,"bold italic"))
penup()
goto(-420,-180)
pendown()
color('black')
write("Baby,You are a gift from God.You are the biggest blessing to my life.\nA man like you shouldn't try so hard to be perfect\ntrust me perfect should try to be you",font=("verdana",15,"italic"))
penup()
goto(-100,-250)
pendown()
color('red')
write("I love you from the bottom of my heart ^>^",font=("Dancing script",20,"bold italic"))

done()
